vm:
  host: 192.168.142.134

spring:
  application:
    name: zipkin-client-service
  rabbitmq:
    port: 5672
    host: ${vm.host}
    username: admin
    password: admin

  zipkin:
    base-url: http://${vm.host}:9411
    enabled: true
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1.0  #100%取样

  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456

  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        max_fetch_depth: 2

  h2:
    console:
      path: /h2-console
      enabled: true
logging:
  level:
    io.danielpine.github.repository: debug
  config:
    classpath: logback-spring.xml