server:
  #配置端口号
  port: 8686

spring:
  application:
    name: zipkin-client

  rabbitmq:
    port: 5672
    host: 192.168.142.136
    username: admin
    password: admin

  zipkin:
    base-url: http://192.168.142.136:9411
    enabled: true
    service:
      name: zipkin-client-service   #默认会显示Spring Application Name，但是可以覆盖Service地址
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1.0  #100%取样

  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456

  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      path: /h2-console
      enabled: true

logging:
  level:
    config: classpath:logback-spring.xml
